apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agency-ingress
  namespace: agency-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx   # Use the nginx ingress controller
  rules:
    - host: ""    
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agency-kah-service  
                port:
                  number: 81
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: agency-kah-service   
                port:
                  number: 81
